version: '3.8'

services:
  backend-ai:
    image: ghcr.io/vijai-veerapandian/myweather-app-backend-ai:latest
    container_name: backend-ai
    ports:
      - "5000:5000" # Expose backend on host port 5000
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CORS_ORIGIN=http://${HOST_IP}:3000
      - HOST_IP=${HOST_IP}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network

  frontend:
    image: ghcr.io/vijai-veerapandian/myweather-app-frontend:latest
    container_name: frontend
    ports:
      - "3000:3000" # Expose frontend on host port 3000
    environment:
      - HOST_IP=${HOST_IP}
      - REACT_APP_BACKEND_AI_URL=http://${HOST_IP}:5000
      - REACT_APP_GEO_API_URL=${REACT_APP_GEO_API_URL}
      - REACT_APP_RAPIDAPI_KEY=${REACT_APP_RAPIDAPI_KEY}
      - REACT_APP_RAPIDAPI_HOST=${REACT_APP_RAPIDAPI_HOST}
      - REACT_APP_WEATHER_API_URL=${REACT_APP_WEATHER_API_URL}
      - REACT_APP_WEATHER_API_KEY=${REACT_APP_WEATHER_API_KEY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network

  # loki:
  #   image: grafana/loki:2.8.2
  #   container_name: loki
  #   ports:
  #     - "3100:3100"
  #   command: -config.file=/etc/loki/local-config.yaml
  #   networks:
  #     - app-network

  # promtail:
  #   image: grafana/promtail:2.8.2
  #   container_name: promtail
  #   volumes:
  #     - /var/log:/var/log
  #     - ./promtail-config.yml:/etc/promtail/config.yml
  #   networks:
  #     - app-network

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge