server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      # Filter logs to include only specific containers
      - source_labels: [__meta_docker_container_name]
        regex: ^(react-app|redis|postgres|backend-api|backend-ai|prometheus|grafana)$
        action: keep
