{
 "title": "Loki-centralized-logs-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Frontend-logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"frontend\"} |= ``"
    }
   ]
  },
  {
   "title": "Backend-logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"backend\"} |= ``"
    }
   ]
  },
  {
   "title": "loki-logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"loki\"} |= ``"
    }
   ]
  },
  {
   "title": "cadvisor-logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"cadvisor\"} |= ``"
    }
   ]
  }
 ]
}