apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o manifests/
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o manifests/
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: frontend
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - image: ghcr.io/vijai-veerapandian/myweather-frontend:1.0
          name: myweather-frontend
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
