# /home/vboxuser/apps-dev/myweather-app3/testv4/myweather-app/loki-config/local-config.yaml
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /tmp/loki # Directory Loki will use inside the container
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093 # Adjust if you add Alertmanager

# By default, Loki will send anonymous, but aggregated usage stats to Grafana Labs.
# Stats help us learn about commonly used features, error rates, and performance characteristics.
# Refer to https://grafana.com/docs/loki/latest/configuration/#analytics
analytics:
  reporting_enabled: false