# /home/vboxuser/2-local-dev-repos/myweather-app3/testv4/myweather-app/prometheus-config/prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Scrape Loki
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  # Scrape Promtail
  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']

  # Scrape Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  # Scrape Backend
  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:5000']


