apiVersion: v1
data:
    GEMINI_API_KEY: ENC[AES256_GCM,data:NSmgcI4S1FiLRYbFsS+PfZpbxkx4y+Tjf73mnrC46XS15gS5cYmbSgFKCtS4HwSUV6jhxA==,iv:CFlrBjcdOKZQ/SQWB1g7LhK4Qm68srGSL3yj/TK4Ibg=,tag:M7v/PvprZVvGrvVJRV19HQ==,type:str]
    REACT_APP_RAPIDAPI_KEY: ENC[AES256_GCM,data:E5AcDYKR7nf++1uxJEOwSvR0ZX3Yz5L3aFxA3KTzoF7N9/ks964ZFpxi0xWrZcnZk8UJLtnzFteXA6D2NUnm/jc3x50=,iv:j47jshHtVrpngoke4c9w9ugvGN/7YBwG2liysf9bfMw=,tag:8v+SubNpjUddT4OwMMa7ig==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: backend-secret
    namespace: myweather
sops:
    age:
        - recipient: age1gzv4ljy9xsqj45jjcdlcw3kmxs9h09dnkmcy0lvf8r9qx7ypr4vqqdxjt6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNREVHWVdXZStkTW9JcVB1
            a3haNXhPTnlRS3lSVlJwRFh3MWF6Nkd5bWpRClpKZDN2ZERwejN2QWNVTDEyREpW
            ZHZOcGlJYlVkZW52VkFmWU5IV3FOaWMKLS0tIHVYbXpIRG1ObEcvNGFyZ2NEcGhB
            TzZDbXZqK3pHNHNpeHVnWGZ3blloV0UKcq/fTCGu88Un35TOKTH8gzTtzvY1bfIY
            ttENEXzDIzOwJdpPzSkJRRwl08gTrOiXH6TcAnWm/vL/5kiw52MQMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-23T22:19:37Z"
    mac: ENC[AES256_GCM,data:d5Pb0PV17V2ZR24CumImcbxKHuL8OkM6sjBc+gsZ0qSOHsmc1Lt4URklQNIKhuogJucp3yefDvvmcwsEtHFn6eKj9uDnk3YU7VnvRLWA6RaHpkuP82tlQOCfxdYdwclYtJrDx+IbpdCbwQqarFkQH0MzRr7UuuUkPnEBn3f2r80=,iv:ImRcbFrZBXHSXBSB9N3OfCvKGHls4bnvE8ROljfWg98=,tag:bGltQlGpXtHJgHKJjmXgig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
